### ISSUE TITLE
Failed to load the compare-files package

### ISSUE THREAD

**Issue by thibmaek** [floydpink/atom-compare-files#16]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [compare-files](https://github.com/floydpink/atom-compare-files) package, v0.4.1

### Stack Trace

Failed to load the compare-files package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/thibaultmaekelbergh/Dropbox/Mackup/.atom/packages/compare-files/lib/compare-files-view.js:26:32)
    at /Users/thibaultmaekelbergh/Dropbox/Mackup/.atom/packages/compare-files/lib/compare-files-view.js:38:5
    at Object.<anonymous> (/Users/thibaultmaekelbergh/Dropbox/Mackup/.atom/packages/compare-files/lib/compare-files-view.js:188:5)
    at Object.<anonymous> (/Users/thibaultmaekelbergh/Dropbox/Mackup/.atom/packages/compare-files/lib/compare-files-view.js:190:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jslint",
      "emmet",
      "unregistered",
      "compass",
      "quippet",
      "autocomplete-paths",
      "autocomplete-plus"
    ],
    "themes": [
      "yeti-ui",
      "kimbie-light"
    ],
    "ignoredNames": [
      "node_modules",
      ".DS_Store",
      "npm-debug.log"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
atom-bootstrap3, v1.2.0
atom-html-preview, v0.1.6
atom-spotify, v1.2.0
atom-terminal, v0.7.0
backbonejs-snippets, v0.4.1
close-tags, v0.2.0
compare-files, v0.4.1
editor-stats, v0.17.0
editorconfig, v0.3.3
error-status, v0.3.3
file-icons, v1.5.3
git-log, v0.3.0
git-plus, v4.4.12
gulp-helper, v2.0.0
gulp-snippets, v0.6.1
iTunes, v0.2.0
jsonlint, v1.0.2
kimbie-light, v1.0.1
language-swift, v0.3.0
laravel, v0.4.2
linter, v0.12.0
linter-flow, v0.1.4
linter-jshint, v0.1.1
linter-php, v0.0.12
linter-scss-lint, v0.0.14
open-in, v3.1.0
open-in-browser, v0.4.3
path, v0.4.1
remote-edit, v1.7.2
remote-sync, v2.4.1
ssh-config, v0.10.0
swift-playground, v0.2.0
travis-ci-status, v0.13.0
uglify, v1.2.0
weather-package, v1.5.1
web-browser, v1.4.3
yeti-ui, v0.1.6

# Dev
No dev packages
```

**Comment by targeter21** [comment]
Same as #30. Since that has more activity, I will focus attention there.
