### ISSUE TITLE
Uncaught TypeError: path must be a string

### ISSUE THREAD

**Issue by TwanoO67** [floydpink/atom-compare-files#20]
Hi,

I'm not able to get your plugin working, always getting "path must be a string" error, on fs.js...
Is there a prerequisite I don't know about?

Regards,
Antoine

[Enter steps to reproduce below:]

1. Selecting to files in a folder ( for information my project are created by the plugin "git-projects", but I don't know if that's relevant)
2. Right-Click on Compare Files

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.2
**Thrown From**: [compare-files](https://github.com/floydpink/atom-compare-files) package, v0.4.1

### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:519

TypeError: path must be a string
  at TypeError (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:396:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at CompareFilesView.module.exports.CompareFilesView.readAndProcessFiles (/Users/aweber/.atom/packages/compare-files/lib/compare-files-view.js:147:30)
  at CompareFilesView.module.exports.CompareFilesView.renderDiffContent (/Users/aweber/.atom/packages/compare-files/lib/compare-files-view.js:165:12)
  at /Users/aweber/.atom/packages/compare-files/lib/compare-files.js:65:30
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/lodash/dist/lodash.js:5519:43

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "remote-edit",
      "Remote-FTP"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.12.0
compare-files, v0.4.1
git-control, v0.1.9
git-projects, v1.13.0
linter, v0.12.1
symbols-tree-view, v0.9.2

# Dev
No dev packages
```

**Comment by targeter21** [comment]
I just put in a slew of updates to bring it up to speed with Atom 1.0. Please try updating thanks!

**Comment by targeter21** [comment]
I don't believe this is an issue anymore. Feel free to reopen if this is still present. Make sure to uninstall and reinstall the plugin so the latest version is 0.6.2.

**Comment by lbodurka** [comment]
this is still an issue;/|


undefined...undefined
1 update
Uncaught TypeError: path must be a string
fs.js:549
Hide Stack Trace
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at CompareFilesView.module.exports.CompareFilesView.readAndProcessFiles (/Users/lbodurka/.atom/packages/compare-files/lib/compare-files-view.js:146:30)
    at CompareFilesView.module.exports.CompareFilesView.renderDiffContent (/Users/lbodurka/.atom/packages/compare-files/lib/compare-files-view.js:164:12)
    at /Users/lbodurka/.atom/packages/compare-files/lib/compare-files.js:84:34
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/lodash/dist/lodash.js:5520:43
The error was thrown from the compare-files package. This issue has already been reported.
View Issue

**Comment by Zarbuz** [comment]
Have the same problem ... 

**Atom Version**: 1.3.2
**System**: Unknown Windows Version
**Thrown From**: [compare-files](https://github.com/floydpink/atom-compare-files) package, v0.6.2


### Stack Trace

Uncaught TypeError: path must be a string

```
At fs.js:549

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at CompareFilesView.module.exports.CompareFilesView.readAndProcessFiles (C:\Users\Nicolas Perrier\.atom\packages\compare-files\lib\compare-files-view.js:146:30)
    at CompareFilesView.module.exports.CompareFilesView.renderDiffContent (C:\Users\Nicolas Perrier\.atom\packages\compare-files\lib\compare-files-view.js:164:12)
    at C:\Users\Nicolas Perrier\.atom\packages\compare-files\lib\compare-files.js:84:34
    at C:\Users\Nicolas Perrier\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\cheerio\node_modules\lodash\dist\lodash.js:5520:43
```

### Commands

```
     -0:04.7.0 compare-files:compare (span.name.icon.icon-file-text)
```

### Installed Packages

```coffee
# User
compare-files, v0.6.2

# Dev
No dev packages
```
