### ISSUE TITLE
Failed to load the compare-files package

### ISSUE THREAD

**Issue by bobber205** [floydpink/atom-compare-files#22]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.9.5
**Thrown From**: [compare-files](https://github.com/floydpink/atom-compare-files) package, v0.4.1

### Stack Trace

Failed to load the compare-files package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/alexwait/.atom/packages/compare-files/lib/compare-files-view.js:26:32)
    at /Users/alexwait/.atom/packages/compare-files/lib/compare-files-view.js:38:5
    at Object.<anonymous> (/Users/alexwait/.atom/packages/compare-files/lib/compare-files-view.js:188:5)
    at Object.<anonymous> (/Users/alexwait/.atom/packages/compare-files/lib/compare-files-view.js:190:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "term",
      "autoclose-html",
      "angularjs",
      "atom-angularjs",
      "editor-stats",
      "jsonlint",
      "turbo-javascript",
      "atom-jshint",
      "jshint"
    ],
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
atom-lint, v0.20.1
atomatigit, v1.3.0
auto-update-packages, v0.2.2
autocomplete-css, v0.6.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.1
autocomplete-snippets, v1.3.0
big-cursor, v0.1.0
compare-files, v0.4.1
fancy-new-file, v0.7.0
file-type-icons, v0.5.4
git-grep, v0.9.0
git-log, v0.3.0
highlight-selected, v0.9.2
html-helper, v0.2.3
html2haml, v0.8.0
jsformat, v0.8.0
language-haml, v0.20.0
linter, v0.12.1
pretty-json, v0.3.3
project-manager, v1.15.5
project-switcher, v0.2.1
quick-move-file, v0.7.0
run-command, v0.1.1
set-syntax, v0.2.1
ssh-config, v0.10.1
url-encode, v0.2.0
uuidgen, v1.2.0

# Dev
No dev packages
```

**Comment by JamesGould123** [comment]
Why did you close this, what answer did you come to?

**Comment by bobber205** [comment]
It was because I was in atom 1.0 preview mode
