### ISSUE TITLE
Uncaught TypeError: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by piaolingxue** [floydpink/atom-compare-files#23]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: [compare-files](https://github.com/floydpink/atom-compare-files) package, v0.4.1

### Stack Trace

Uncaught TypeError: Cannot read property 'find' of undefined

```
At /Users/libin/.atom/packages/compare-files/lib/compare-files.js:18

TypeError: Cannot read property 'find' of undefined
  at resetStatusBar (/Users/libin/.atom/packages/compare-files/lib/compare-files.js:18:31)
  at setStatusMessage (/Users/libin/.atom/packages/compare-files/lib/compare-files.js:22:3)
  at atom-workspace.compare (/Users/libin/.atom/packages/compare-files/lib/compare-files.js:52:5)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:04.4.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:01.2.0 core:confirm (atom-text-editor.editor.mini)
     -0:01.2.0 compare-files:compare (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "status-bar"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.1.0
color-picker, v1.5.0
compare-files, v0.4.1
elixir-cmd, v0.2.3
iex, v0.8.6
language-ansible, v0.1.3
language-crontab, v0.1.0
language-docker, v1.1.3
language-elixir, v0.3.4
language-generic-config, v0.1.4
language-ini, v1.10.0
language-nagios, v0.2.0
linter, v0.12.0
markdown-format, v2.5.0
remote-atom, v1.2.0
remote-edit, v1.7.2
script, v2.18.0

# Dev
No dev packages
```

**Comment by targeter21** [comment]
I just put in a slew of updates to bring it up to speed with Atom 1.0. Please try updating thanks!

**Comment by targeter21** [comment]
Was able to reproduce this issue and fix it. The latest version should be fine now.
