### ISSUE TITLE
Failed to load the compare-files package

### ISSUE THREAD

**Issue by despairblue** [floydpink/atom-compare-files#30]
[Enter steps to reproduce below:]

Happens when opening atom 0.206.0

**Atom Version**: 0.206.0
**System**: linux 3.14.43-2-lts
**Thrown From**: [compare-files](https://github.com/floydpink/atom-compare-files) package, v0.4.1

### Stack Trace

Failed to load the compare-files package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/home/despairblue/.atom/packages/compare-files/lib/compare-files-view.js:26:32)
    at /home/despairblue/.atom/packages/compare-files/lib/compare-files-view.js:38:5
    at Object.<anonymous> (/home/despairblue/.atom/packages/compare-files/lib/compare-files-view.js:188:5)
    at Object.<anonymous> (/home/despairblue/.atom/packages/compare-files/lib/compare-files-view.js:190:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "welcome",
      "metrics",
      "autocomplete",
      "incremental-search",
      "Tern",
      "grunt-runner",
      "tree-view-open-files",
      "tree-view-breadcrumb",
      "atomatigit",
      "themed-settings",
      "linter-scspell",
      "filetype-color",
      "atom-pair",
      "linter-eslint",
      "es-navigation",
      "autocomplete",
      "tab-smart-sort",
      "starred-package-installer",
      "zentabs",
      "linter-jshint",
      "block-cursor",
      "test-status",
      "minimap",
      "minimap-color-highlight",
      "minimap-find-and-replace",
      "minimap-git-diff",
      "minimap-highlight-selected",
      "travis-ci-status",
      "pane-layout-plus",
      "symbols-tree-view",
      "package-cop",
      "navigate",
      "markdown-scroll-sync"
    ],
    "projectHome": "/home/despairblue/vcs/git/",
    "destroyEmptyPanes": false,
    "autoHideMenuBar": true,
    "ignoredNames": [
      "SCENE"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-color-highlight, v3.0.9
atom-fuzzy-grep, v0.2.0
atom-ternjs, v0.6.4
atom-zeal, v0.1.0
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
block-travel, v1.0.2
bug-report, v0.7.0
color-picker, v2.0.4
compare-files, v0.4.1
docblockr, v0.7.2
file-icons, v1.5.7
git-log, v0.4.1
go-plus, v3.3.11
grammar-token-limit, v0.1.1
highlight-selected, v0.9.3
indentation-indicator, v0.5.1
javascript-snippets, v1.0.0
keybinding-cheatsheet, v0.0.9
language-tss, v0.4.0
latex, v0.24.1
linter, v0.12.6
linter-coffeelint, v0.3.1
linter-htmlhint, v0.0.16
linter-js-standard, v0.2.5
linter-js-yaml, v1.0.1
linter-puppet-lint, v0.2.9
linter-shellcheck, v0.0.8
notifications, v0.49.0
package-sync, v0.2.0
pdf-view, v0.22.0
project-manager, v1.15.8
regex-railroad-diagram, v0.7.4
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by mgarciaisaia** [comment]
Same happens on OS X

**Comment by baelter** [comment]
+1

**Comment by suda** [comment]
:+1:

**Comment by pschulz** [comment]
Same on 
Atom Version: 0.207.0

**Comment by eburi** [comment]
Same here: Mac OSX, Atom 0.207.0
:+1:

**Comment by SethG911** [comment]
Same on Windows 8.1.

**Comment by halleycarleton** [comment]
+1 Ubuntu 14.04 - Atom 0.209.0

It seems this package uses deprecated context menu CSON formatting. It also stores it's stylesheets in the wrong directory.

**Comment by balihoo-aharl** [comment]
Same error in Atom 1.0 on OS X

**Comment by targeter21** [comment]
I just put in a slew of updates to bring it up to speed with Atom 1.0. Please try updating thanks!

**Comment by Joeboyc2** [comment]
Hi @targeter21,

i have tried the package with atom 1.0.2 and it still has this issue, here is my stack trace:

Cannot find module 'lodash'
Hide Stack Trace
Error: Cannot find module 'lodash'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\%username%\AppData\Local\atom\app-1.0.2\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\%username%\.atom\packages\atom-compare-files-master\lib\compare-files.js:11:9)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\%username%\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\%username%\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:709:34)
  at C:\Users\%username%\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:188:28
  at Package.module.exports.Package.measure (C:\Users\%username%\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:165:15)
  at Package.module.exports.Package.load (C:\Users\%username%\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:179:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\%username%\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package-manager.js:372:14)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\%username%\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package-manager.js:336:14)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\%username%\AppData\Local\atom\app-1.0.2\resources\app.asar\src\atom.js:642:21)
  at Object.<anonymous> (C:\Users\%username%\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\%username%\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\%username%\AppData\Local\atom\app-1.0.2\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///C:/Users/%username%/AppData/Local/atom/app-1.0.2/resources/app.asar/static/index.js:96:23)
  at window.onload (file:///C:/Users/%username%/AppData/Local/atom/app-1.0.2/resources/app.asar/static/index.js:36:7)

**Comment by targeter21** [comment]
@Joeboyc2 What version of the compare-files plugin do you have? I just installed Atom and the plugin on Windows 7 and did not encounter the error. If you uninstall and reinstall the plugin, do you still see the problem?

**Comment by Joeboyc2** [comment]
Hi @targeter21,

im not able to use the package manager due to the proxy at my work so i downloaded the zip and unpacked it in the packages folder.

Prehaps this is the wrong way to do it....

**Comment by Joeboyc2** [comment]
Hi @targeter21 

i've got it working now, used the apm install from within the folder and this has configured it correctly.

thank you for your help

**Comment by targeter21** [comment]
Glad to hear it!

**Comment by Knochi** [comment]
Same Problem here with manual install... any chance to get it working manually?
