### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NeoSelcev** [floydpink/atom-compare-files#31]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [compare-files](https://github.com/floydpink/atom-compare-files) package, v0.4.1

### Stack Trace

Failed to load the compare-files package

```
At Cannot find module 'lodash'

Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\Admin\AppData\Local\atom\app-1.0.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\Admin\.atom\packages\atom-compare-files-master\lib\compare-files.js:12:9)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (C:\Users\Admin\AppData\Local\atom\app-1.0.0\resources\app.asar\src\babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
default-language, v0.2.0
monokai, v0.14.0

# Dev
No dev packages
```

**Comment by targeter21** [comment]
I just put in a slew of updates to bring it up to speed with Atom 1.0. Please try updating thanks!

**Comment by targeter21** [comment]
The issue stemmed from other programmatic issues. I did see the issue previously, but do not anymore.
