### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by ahouchens** [floydpink/atom-compare-files#35]
[Enter steps to reproduce below:]

1.Select two files in different folders for comparing.
2. Their permissions are 644 (which includes owner read)

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [compare-files](https://github.com/floydpink/atom-compare-files) package, v0.6.2

### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, read

```
At fs.js:591

Error: EISDIR: illegal operation on a directory, read
  at Error (native)
  at Object.fs.readSync (fs.js:596:19)
  at Object.fs.readFileSync (fs.js:428:28)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at CompareFilesView.module.exports.CompareFilesView.readAndProcessFiles (/Users/ahouchens/.atom/packages/compare-files/lib/compare-files-view.js:146:30)
  at CompareFilesView.module.exports.CompareFilesView.renderDiffContent (/Users/ahouchens/.atom/packages/compare-files/lib/compare-files-view.js:164:12)
  at /Users/ahouchens/.atom/packages/compare-files/lib/compare-files.js:84:34
  at /Users/ahouchens/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/lodash/dist/lodash.js:5520:43

```

### Commands

```
     -0:30.5.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  3x -0:28.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:25.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:25.5.0 compare-files:compare (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "save-session"
    ],
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
compare-files, v0.6.2
minimap, v4.12.2
monokai, v0.17.0
project-manager, v1.15.11

# Dev
No dev packages
```

**Comment by targeter21** [comment]
I've usually only seen this error when accidentally trying to compare a directory. Could you post an animation of the issue being reproduced? Looks like the root issue is something you selected fs didn't like.

**Comment by timkrins** [comment]
I received this error when *purposefully* trying to compare two directories ;)

**Comment by anand853** [comment]
i hit the same error.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [compare-files](https://github.com/atom-compare-files/atom-compare-files) package 0.8.1


### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, read

```
At fs.js:731

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at tryReadSync (fs.js:486:20)
    at Object.fs.readFileSync (fs.js:534:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at CompareFilesView.module.exports.CompareFilesView.readAndProcessFiles (/packages/compare-files/lib/compare-files-view.js:148:30)
    at CompareFilesView.module.exports.CompareFilesView.renderDiffContent (/packages/compare-files/lib/compare-files-view.js:166:12)
    at /packages/compare-files/lib/compare-files-view.js:119:14)
    at /packages/compare-files/lib/compare-files.js:62:14
    at Workspace.module.exports.Workspace.openURIInPane (/app.asar/src/workspace.js:501:22)
    at Workspace.module.exports.Workspace.open (/app.asar/src/workspace.js:436:19)
    at /packages/compare-files/lib/compare-files.js:85:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1170:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:333:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  2x -2:08.9.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:27.4.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -1:14.3.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:58.9.0 tree-view:expand-item (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:58.1.0 core:move-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:57.8.0 tree-view:collapse-directory (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:57.2.0 tree-view:expand-item (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:43 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -0:39.6.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:26.2.0 compare-files:compare (span.name.icon.icon-repo)
```

### Non-Core Packages

```
atom-clock 0.1.13 
autoclose-html 0.23.0 
busy-signal 1.4.3 
compare-files 0.8.1 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.2.4 
pretty-json 1.6.4 
split-diff 1.3.0 
```
