### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/laurentdelacerda/Desktop/editor_'

### ISSUE THREAD

**Issue by laurent-d** [floydpink/atom-compare-files#37]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [compare-files](https://github.com/floydpink/atom-compare-files) package, v0.6.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/laurentdelacerda/Desktop/editor_'

```
At fs.js:97

Error: ENOENT: no such file or directory, open '/Users/laurentdelacerda/Desktop/editor_'
  at Error (native)
  at Object.fs.openSync (fs.js:549:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
  at Object.fs.readFileSync (fs.js:397:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:384:29)
  at CompareFilesView.module.exports.CompareFilesView.readAndProcessFiles (/Users/laurentdelacerda/.atom/packages/compare-files/lib/compare-files-view.js:147:30)
  at CompareFilesView.module.exports.CompareFilesView.renderDiffContent (/Users/laurentdelacerda/.atom/packages/compare-files/lib/compare-files-view.js:164:12)
  at /Users/laurentdelacerda/.atom/packages/compare-files/lib/compare-files.js:84:34
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/cheerio/node_modules/lodash/dist/lodash.js:5520:43

```

### Commands

```
     -4:28.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  7x -3:58.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -3:52.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:53.7.0 compare-files:compare (atom-text-editor.editor.is-focused)
     -0:14.3.0 application:add-project-folder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:01.6.0 compare-files:compare (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.multi-select)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.13.6
atom-minify, v0.4.2
color-picker, v2.0.13
compare-files, v0.6.2
minimap, v4.13.4
pigments, v0.15.0
remote-edit, v1.8.21

# Dev
No dev packages
```

**Comment by suhrmann** [comment]
Dito.
[Enter steps to reproduce below:]
 Selected 2 files and then used Ctrl+Alt+C to compare --> Exception.


**Atom Version:** 1.21.1 x64
**System:** Windows 10 Pro x64, 1709
**Thrown From:** compare-files package, v0.8.1

### Stack Trace

```
Uncaught (in promise) Error: ENOENT: no such file or directory, open 'C:\Users\...\file1.cpp'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at CompareFilesView.module.exports.CompareFilesView.readAndProcessFiles (C:\Users\thechosenone\.atom\packages\compare-files\lib\compare-files-view.js:148:30)
    at CompareFilesView.module.exports.CompareFilesView.renderDiffContent (C:\Users\thechosenone\.atom\packages\compare-files\lib\compare-files-view.js:166:12)
    at new CompareFilesView (C:\Users\thechosenone\.atom\packages\compare-files\lib\compare-files-view.js:119:14)
    at C:\Users\thechosenone\.atom\packages\compare-files\lib\compare-files.js:62:14
    at Workspace.createItemForURI (C:\Users\thechosenone\AppData\Local\atom\app-1.21.1\resources\app\src\workspace.js:1323:28)
    at Workspace.<anonymous> (C:\Users\thechosenone\AppData\Local\atom\app-1.21.1\resources\app\src\workspace.js:1129:42)
    at Generator.next (<anonymous>)
    at step (C:\Users\thechosenone\AppData\Local\atom\app-1.21.1\resources\app\src\workspace.js:11:279)
    at C:\Users\thechosenone\AppData\Local\atom\app-1.21.1\resources\app\src\workspace.js:11:449
    at Workspace.<anonymous> (C:\Users\thechosenone\AppData\Local\atom\app-1.21.1\resources\app\src\workspace.js:11:105)
    at HTMLElement.compare (C:\Users\thechosenone\.atom\packages\compare-files\lib\compare-files.js:85:11)
    at CommandRegistry.handleCommandEvent (C:\Users\thechosenone\AppData\Local\atom\app-1.21.1\resources\app\src\command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\thechosenone\AppData\Local\atom\app-1.21.1\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\thechosenone\AppData\Local\atom\app-1.21.1\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\thechosenone\AppData\Local\atom\app-1.21.1\resources\app\src\window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (C:\Users\thechosenone\AppData\Local\atom\app-1.21.1\resources\app\src\window-event-handler.js:3:65)
```

### Installed Packages
```
compare-files 0.8.1
markdown-preview-plus 2.4.16
```
