### ISSUE TITLE
Uncaught TypeError: Cannot read property 'selectedPaths' of null

### ISSUE THREAD

**Issue by rpietro** [floydpink/atom-compare-files#38]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [compare-files](https://github.com/floydpink/atom-compare-files) package, v0.6.2

### Stack Trace

Uncaught TypeError: Cannot read property 'selectedPaths' of null

```
At /Users/rpietro/.atom/packages/compare-files/lib/compare-files.js:70

TypeError: Cannot read property 'selectedPaths' of null
  at atom-workspace.compare (/Users/rpietro/.atom/packages/compare-files/lib/compare-files.js:70:62)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
  6x -0:41.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:39.2.0 settings-view:open (atom-text-editor.editor.mini.is-focused)
  2x -0:38.8.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:38.7.0 settings-view:open (div.settings-view.pane-item)
  2x -0:38.7.0 blur (div.settings-view.pane-item)
     -0:35.3.0 click (a.icon.icon-plus)
     -0:35.2.0 blur (div.settings-view.pane-item)
     -0:32.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:28.2.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:22.3.0 click (button.btn.btn-info.icon.icon-cloud-download.install-button)
     -0:22.3.0 blur (button.btn.btn-info.icon.icon-cloud-download.install-button.is-installing)
     -0:06.2.0 core:close (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-light-theme.theme-one-dark-ui)
     -0:04.5.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-light-theme.theme-one-dark-ui)
     -0:01.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 compare-files:compare (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-light-theme.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-light-theme"
    ],
    "disabledPackages": [
      "markdown-preview-plus",
      "language-pfm",
      "atom-terminal"
    ],
    "projectHome": "/Users/rpietro/Desktop"
  }
}
```

### Installed Packages

```coffee
# User
atom-commander, v0.4.2
auto-update-packages, v1.0.0
autocomplete-bibtex, v0.6.1
browser-plus, v0.0.35
compare-files, v0.6.2
formatter-coffeescript, v0.1.1
ginger, v0.1.1
isearch, v0.1.12
language-coffeescript-html, v0.46.0
language-todotxt, v0.6.1
linter-coffeescript, v1.0.0
repl-term, v0.2.2
sort-lines, v0.11.0
wordcount, v2.3.0

# Dev
No dev packages
```

**Comment by ParitoshBh** [comment]
Can you share steps to reproduce this? I know its too late (2 years!) but if you can, it'd be great!
