### ISSUE TITLE
Uncaught TypeError: Cannot read property 'selectedPaths' of undefined

### ISSUE THREAD

**Issue by zerolaser** [floydpink/atom-compare-files#57]
[Enter steps to reproduce:]
I was comparing two aws Cloudformation templates files split in two panes. then I encountered this error.
1. ...
2. ...

Probably could be the reason I haven't selected the second file for comparing... tried replicating did not get it.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [compare-files](https://github.com/atom-compare-files/atom-compare-files) package 0.8.1

### Stack Trace

Uncaught TypeError: Cannot read property 'selectedPaths' of undefined

```
At /Users/vkris9/.atom/packages/compare-files/lib/compare-files.js:75

TypeError: Cannot read property 'selectedPaths' of undefined
    at /packages/compare-files/lib/compare-files.js:75:62)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at SelectListView.didClickItem (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:228:16)
    at ListItemView.onclick (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:168:37)
    at ListItemView.didClick (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:361:16)
```

### Commands

```
     -0:49.9.0 application:new-file (atom-pane.pane.active)
     -0:40.8.0 core:paste (input.hidden-input)
     -0:31.2.0 tabs:split-right (div.title)
     -0:16.5.0 core:paste (input.hidden-input)
     -0:14.1.0 command-palette:toggle (input.hidden-input)
     -0:10.7.0 compare-files:compare (input.hidden-input)
```

### Non-Core Packages

```
compare-files 0.8.1 
```

**Comment by maberg** [comment]
Easily reproduced: Atom 1.26.1 Windows x64, install package compare-files. Create a new file containing the line "foo1", create another new file containing the line "foo2". Run compare

**Comment by mascheck** [comment]
This seem to happen when the files are not saved anywhere

**Comment by maberg** [comment]
Yes, saving the files before running compare will avoid the error
